networks:
  smart-doc-network:
    driver: bridge

volumes:
  app_data:
    driver: local

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: smart-doc-backend
    ports:
      - "8000:8000"
    networks:
      - smart-doc-network
    volumes:
      - app_data:/app/data
      - ../backend/uploads:/app/backend/uploads
      - ../documents.db:/app/data/documents.db
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///app/data/documents.db
      - UPLOAD_DIR=/app/backend/uploads
      - DEBUG=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      target: development
    container_name: smart-doc-frontend
    ports:
      - "3000:3000"
    networks:
      - smart-doc-network
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
